<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1      2      3      4</name>
   <tag></tag>
   <elementGuidId>724e3a73-9db1-4437-b437-96eab9853907</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      1
      2
      3
      4
      5
      6
      7
      8
      9
      10

    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;container&quot;]/form[1]/div[@class=&quot;field&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;select&quot;]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
